on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Lint

jobs:
  lint:
    name: Check Code Quality
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Download ktlint
      run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.3.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
    - name: run ktlint
      run: |
        ktlint --reporter=checkstyle,output=build/ktlint-report.xml
      continue-on-error: true
    - uses: yutailang0119/action-ktlint@v4
      with:
        report-path: build/*.xml
        ignore-warnings: true
        continue-on-error: false
